### ISSUE TITLE
feat: implement `ark-snark` `SNARK` trait

### ISSUE THREAD

**Issue by Autoparallel** [microsoft/Spartan2#15]
## Proposal
To make Spartan compatible with other proving backends, it would be helpful to implement the [`ark-snark` `SNARK` trait](https://github.com/arkworks-rs/snark/blob/202b9e02b808d1d15823298b8ac16f5c54ae4ef6/snark/src/lib.rs). This would, for example, allow for Spartan to be used alongside [Sonobe](https://github.com/privacy-scaling-explorations/sonobe/) as opposed to the other SNARKs to choose from. Current list of known implementations are:
- groth16
- marlin
- gm17
- gemini
- ripp
(see [here](https://github.com/arkworks-rs)).

Those at Sonobe are [definitely interested](https://github.com/privacy-scaling-explorations/sonobe/issues/185). 

## Work to be done
A while back there was a fork of this repo made by the arkworks community: https://github.com/arkworks-rs/spartan

It rests a handful of commits ahead and behind this repository but does not actually implement the necessary trait. Most of the changes are to swap to an arkworks backend in some places.

My guess is that it is not of interest to have this specific crate gutted this far to do this, but perhaps, at least, there could be a feature flag for `arkworks`. 

## More comments
Based on discussion, it seems like swapping out bellpepper for arkworks fields and curves would be the goal here. Not sure if the constraint system would also have to change, but likely will.

## Tasks
These tasks are preliminary thoughts and may need to change.
- [ ] Use `ark-ff` in place of `ff`.
- [ ] Use `ark-ec` for curves.
- [ ] Use `ark-relations` in place of `bellpepper` / `bellpepper-core`
- [ ] Use `ark-snark` to implement `SNARK` trait for Spartan variants.

## Backlink
Original discussion happened [here](https://github.com/microsoft/Spartan/issues/80). May need more discussion before moving forward. 

---

I can at least start trying to do drop in replacements of `ark-*` crates with draft PR and we can monitor along the way.

**Comment by srinathsetty** [comment]
Closing due to lack of activity.
